version: '3'

networks:
  bridgx_net:

services:

  #######################  fe  ########################
  fe:
    container_name: bridgx_fe
    restart: always
    network_mode: "host"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
    build:
      context: .
      dockerfile: ./Dockerfile